### PR TITLE
Fix read name format from FASTQ files with white-space

### LINKED ISSUE #319: FASTQ read name encoding keeps spaces
`FastqReadNameEncoding.getPlainName` parses names in non-Casava format as a whole, letting spaces to be included in the transformed SAM read. Thus, after converting a read-name from such a FASTQ into a SAM/BAM format, the space is included in the read name, generating an invalid file (as far as I know, although neither HTSJDK/GATK complains).

We should do a non-backwards compatible bugfix to trim the read name, storing the information into a custom tag (the CO tag is for the comment, used for the quality line). We can store all the information after the white space, or just the original read name. This should be do soon, and we have to release a new version with the bugfix.

### PR DESCRIPTION
**Pull request by magicDGS**
Closes #319

### CODE REVIEW

File: src/test/java/org/magicdgs/readtools/utils/fastq/FastqReadNameEncodingUnitTest.java [hunk 1]
```diff
@@ -67,6 +76,11 @@
                         "@HWUSI-EAS100R:6:73:941:1973#ATCGA comment",
                         "@HWUSI-EAS100R:6:73:941:1973#ATCGA", false, false, false,
                         new String[] {"ATCGA"}},
+                {FastqReadNameEncoding.ILLUMINA,
+                        "@HWUSI-EAS100R:6:73:941:1973#ACTG/2 comment",
```
Comment (magicDGS) [inline src/test/java/org/magicdgs/readtools/utils/fastq/FastqReadNameEncodingUnitTest.java]: Probably we should also add another test to check how something like "@readName comment#ACTG/2" works...

File: src/test/java/org/magicdgs/readtools/utils/fastq/FastqReadNameEncodingUnitTest.java [hunk 2]
```diff
@@ -105,12 +128,12 @@ public void testGetPlainName(final FastqReadNameEncoding encoding,
...
     @Test(dataProvider = "encodingData")
     public void testUpdateReadFromReadName(final FastqReadNameEncoding encoding,
-            final String readName, final String expextedNormalize, final boolean first,
+            final String readName, final String expectedNormalize, final boolean first,
             final boolean second, final boolean pf, final String[] barcode) throws Exception {
         final GATKRead read = ArtificialReadUtils.createArtificialUnmappedRead(null, null, null);
         FastqReadNameEncoding.updateReadFromReadName(read, readName);
         Assert.assertEquals(read.getName(),
-                plainNameFromExpectedNormalize(expextedNormalize), "incorrect name");
+                plainNameFromExpectedNormalize(expectedNormalize), "incorrect name");
```
Comment (magicDGS) [inline src/test/java/org/magicdgs/readtools/utils/fastq/FastqReadNameEncodingUnitTest.java]: And plainNameFromExpectedNormalize should be removed...
