### PR TITLE
Add argument collection for fixing barcodes in tools

### LINKED ISSUE #137: Arguments for tags should validate that they are correct
As an example, while running the following:

```
java -jar ReadTools.jar ReadsToFastq --input example.bam --output example.fastq --outputFormat PLAIN --rawBarcodeSequenceTags GTTTCGGA
```
An user reported the unexpected error `"UNEXPECTED ERROR: Read attribute GTTTCGGA invalid: attribute names must be non-null two-character Strings matching the pattern /[A-Za-z][A-Za-z0-9]/"`, which should indeed being an user error.

We should validate the tags arguments and blow up with an user exception pointing out the correct format for tags. Maybe this concrete case will be addressed at the same time as #128.

### PR DESCRIPTION
**Pull request by magicDGS**
This reduce the repetition of code for tools requiring fix of barcode tags, closing #128

In addition, it includes some minor/bug fixes:

- Raw barcode tags static Strings in `RTReadUtils`
- Bug fix: validate tag names provided by the user (fixes #137)
- More tests for argument validation

### CODE REVIEW

File: src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java [hunk 1]
```diff
@@ -0,0 +1,255 @@
...
+import scala.Tuple2;
+
+import java.io.Serializable;
+import java.util.ArrayList;
+import java.util.Collections;
+import java.util.List;
+import java.util.Set;
+
+/**
+ * Abstract rgument collection for fixing barcodes that are encoded in different places than the
```
Comment (magicDGS) [inline src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java]: typo: rgument

File: src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java [hunk 2]
```diff
@@ -0,0 +1,255 @@
...
+ * {@link RTReadUtils#RAW_BARCODE_TAG} tag.
+ *
+ * @author Daniel Gomez-Sanchez (magicDGS)
+ */
+public abstract class FixBarcodeAbstractArgumentCollection implements Serializable {
+    private static final long serialVersionUID = 1L;
+
+    @Argument(fullName = RTStandardArguments.RAW_BARCODE_SEQUENCE_TAG_NAME, shortName = RTStandardArguments.RAW_BARCODE_SEQUENCE_TAG_NAME, doc = "Include the barcodes encoded in this tag(s) in the read name. Note: this is not necessary for input FASTQ files.", optional = true,
+            mutex = {RTStandardArguments.USER_READ_NAME_BARCODE_NAME})
```
Comment (magicDGS) [inline src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java]: Because this should be separated in two lines anyway, do it in a more readable way.

File: src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java [hunk 3]
```diff
@@ -0,0 +1,255 @@
...
+    public List<String> rawBarcodeTags = new ArrayList<>(RTReadUtils.RAW_BARCODE_TAG_LIST);
+
+    @Argument(fullName = RTStandardArguments.USER_READ_NAME_BARCODE_NAME, shortName = RTStandardArguments.USER_READ_NAME_BARCODE_NAME, doc = "Use the barcode encoded in SAM/BAM/CRAM read names. Note: this is not necessary for input FASTQ files.", optional = true,
+            mutex = {RTStandardArguments.RAW_BARCODE_SEQUENCE_TAG_NAME})
```
Comment (magicDGS) [inline src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java]: The same as before.

File: src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java [hunk 4]
```diff
@@ -0,0 +1,255 @@
...
+    /**
+     * Fix the barcodes for the pair. Default implementation only fix the
+     * {@link RTReadUtils#RAW_BARCODE_TAG} tag.
+     */
+    protected void fixBarcodeForPair(final GATKRead read1, final GATKRead read2) {
+        RTReadUtils.fixPairTag(RTReadUtils.RAW_BARCODE_TAG, read1, read2);
+    }
+
+    /**
+     * Validate the arguments after parsing. Default implementation check for repeated barcode
```
Comment (magicDGS) [inline src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java]: Move the text from the dot on to the next line.

Comment (magicDGS) [inline src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java]: And add comment about the validity of tags.

File: src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java [hunk 5]
```diff
@@ -0,0 +1,255 @@
...
+                    "contain duplicated tags: " + duplicated);
+        }
+
+        // valid tag names
+        rawBarcodeTags.forEach(rbt -> validateTagArgument(rbt,
+                RTStandardArguments.RAW_BARCODE_SEQUENCE_TAG_NAME));
+    }
+
+    /** Gets a ReadTransformer to fix the barcodes. */
+    protected final ReadTransformer getFixBarcodeReadTransformer() {
```
Comment (magicDGS) [inline src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java]: This should be private if possible.

File: src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java [hunk 6]
```diff
@@ -0,0 +1,255 @@
...
+    @Argument(fullName = RTStandardArguments.USER_READ_NAME_BARCODE_NAME, shortName = RTStandardArguments.USER_READ_NAME_BARCODE_NAME, doc = "Use the barcode encoded in SAM/BAM/CRAM read names. Note: this is not necessary for input FASTQ files.", optional = true,
+            mutex = {RTStandardArguments.RAW_BARCODE_SEQUENCE_TAG_NAME})
+    public boolean useReadNameBarcode = false;
+
+    // cached transformer, initialized if needed
+    private ReadTransformer transformer = null;
+
+    /** Logger for the class. */
+    protected final Logger logger =
+            LogManager.getLogger(FixBarcodeAbstractArgumentCollection.class);
```
Comment (magicDGS) [inline src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java]: Use the current class, not the abstract.

File: src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java [hunk 7]
```diff
@@ -0,0 +1,255 @@
...
+    }
+
+
+    /** Implementation without barcode qualities. */
+    private static final class FixSimpleBarcodeArgumentCollection
+            extends FixBarcodeAbstractArgumentCollection {
+
+        @Override
+        protected List<String> getRawBarcodeQualityTags() {
+            return Collections.emptyList();
```
Comment (magicDGS) [inline src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java]: Add logger debug for this, to make easier debugging.

File: src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java [hunk 8]
```diff
@@ -0,0 +1,255 @@
...
+    }
+
+    /** Implementation with barocde qualities */
+    private static final class FixBarcodeWithQualitiesArgumentCollection
+            extends FixBarcodeAbstractArgumentCollection {
+
+        @Argument(fullName = RTStandardArguments.RAW_BARCODE_QUALITIES_TAG_NAME, shortName = RTStandardArguments.RAW_BARCODE_QUALITIES_TAG_NAME, doc =
+                "Use the qualities encoded in this tag(s) as raw barcode qualities. Requires --"
+                        + RTStandardArguments.RAW_BARCODE_SEQUENCE_TAG_NAME
+                        + ". WARNING: this tag(s) will be removed.", optional = true,
```
Comment (magicDGS) [inline src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java]: Re-format lines and change "removed" for "removed/updated".

File: src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java [hunk 9]
```diff
@@ -0,0 +1,255 @@
...
+/**
+ * Abstract rgument collection for fixing barcodes that are encoded in different places than the
+ * {@link RTReadUtils#RAW_BARCODE_TAG} tag.
+ *
+ * @author Daniel Gomez-Sanchez (magicDGS)
+ */
+public abstract class FixBarcodeAbstractArgumentCollection implements Serializable {
+    private static final long serialVersionUID = 1L;
+
+    @Argument(fullName = RTStandardArguments.RAW_BARCODE_SEQUENCE_TAG_NAME, shortName = RTStandardArguments.RAW_BARCODE_SEQUENCE_TAG_NAME, doc = "Include the barcodes encoded in this tag(s) in the read name. Note: this is not necessary for input FASTQ files.", optional = true,
```
Comment (magicDGS) [inline src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java]: Add note saying that the tags will be removed/updated.

File: src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java [hunk 10]
```diff
@@ -0,0 +1,255 @@
...
+        }
+
+        /** Overrides to fix also the quality tag. */
+        @Override
+        public void fixBarcodeForPair(final GATKRead read1, final GATKRead read2) {
+            super.fixBarcodeForPair(read1, read2);
+            RTReadUtils.fixPairTag(RTReadUtils.RAW_BARCODE_QUALITY_TAG, read1, read2);
+        }
+
+        /** Calls supper and afterwards check barcode tags. */
```
Comment (magicDGS) [inline src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java]: Update javadoc with actual behaviour.

File: src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java [hunk 11]
```diff
@@ -0,0 +1,255 @@
...
+            if (rawBarcodeTags.isEmpty() && !rawBarcodeQualsTags.isEmpty()) {
+                throw new CommandLineException.MissingArgument(
+                        RTStandardArguments.RAW_BARCODE_SEQUENCE_TAG_NAME,
+                        "required if --" + RTStandardArguments.RAW_BARCODE_QUALITIES_TAG_NAME
+                                + "is specified.");
+            }
+
+            // the same number of barcode/quals tags
+            // TODO 20-03-2017: maybe we should allow different number of tags
+            // TODO           : this will require a new implementation, but we do not see any use-case yet
```
Comment (magicDGS) [inline src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java]: Add issue regarding this.

Comment (magicDGS) [inline src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java]: And include link here.

File: src/main/java/org/magicdgs/readtools/tools/barcodes/AssignReadGroupByBarcode.java [hunk 12]
```diff
@@ -163,17 +139,15 @@ public void onTraversalStart() {
      */
     @Override
     protected void apply(final GATKRead read) {
-        logger.debug("Read = {}", () -> read);
```
Comment (magicDGS) [inline src/main/java/org/magicdgs/readtools/tools/barcodes/AssignReadGroupByBarcode.java]: Do not remove the debug line.

File: src/main/java/org/magicdgs/readtools/utils/read/RTReadUtils.java [hunk 13]
```diff
@@ -52,9 +52,14 @@ private RTReadUtils() {}
     /** Zero quality character. */
     public final static char ZERO_QUALITY_CHAR = '!';
 
-    // this is for avoid re-instantation
-    private final static List<String> RAW_BARCODE_TAGS =
-            Collections.singletonList(SAMTag.BC.name());
+    /** Default raw barcode tag (as defined in the SAM specs). Corresponds to {@link SAMTag#BC}. */
+    public final static String RAW_BARCODE_TAG = SAMTag.BC.name();
+
+    public final static String RAW_BARCODE_QUALITY_TAG = SAMTag.QT.name();
```
Comment (magicDGS) [inline src/main/java/org/magicdgs/readtools/utils/read/RTReadUtils.java]: javadoc

File: src/test/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollectionTest.java [hunk 14]
```diff
@@ -0,0 +1,251 @@
...
+        }
+
+        @Override
+        protected Object doWork() {
+            return args.getFixBarcodeReadTransformer().getClass();
+        }
+    }
+
+    @DataProvider(name = "badArgs")
+    public Object[][] getBadArguments() {
```
Comment (magicDGS) [inline src/test/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollectionTest.java]: Use an iterator based provider to avoid this issue, and add with a for loop the same arguments for with/without qualities if they are the same.

File: src/test/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollectionTest.java [hunk 15]
```diff
@@ -0,0 +1,251 @@
...
+    @Test(dataProvider = "badArgs", expectedExceptions = CommandLineException.class)
+    public void testBadArguments(final ArgumentsBuilder args, final boolean fixQuals)
+            throws Exception {
+        args.addArgument("verbosity", "ERROR").addBooleanArgument("QUIET", true);
+        final CommandLineProgram clp = new FixBarcodesCLP(fixQuals);
+        clp.instanceMain(args.getArgsArray());
+    }
+
+    @DataProvider(name = "goodArgs")
+    public Object[][] getGoodArguments() {
```
Comment (magicDGS) [inline src/test/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollectionTest.java]: the same as before.

File: src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java (hunk 1 above)
Comment (magicDGS) [inline src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java]: Done.

File: src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java (hunk 9 above)
Comment (magicDGS) [inline src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java]: Done.

File: src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java (hunk 2 above)
Comment (magicDGS) [inline src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java]: Done.

File: src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java (hunk 3 above)
Comment (magicDGS) [inline src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java]: Done.

File: src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java (hunk 6 above)
Comment (magicDGS) [inline src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java]: Done.

File: src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java (hunk 4 above)
Comment (magicDGS) [inline src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java]: Done.

File: src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java (hunk 5 above)
Comment (magicDGS) [inline src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java]: Changed to package-private and visible for testing.

File: src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java (hunk 7 above)
Comment (magicDGS) [inline src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java]: Done.

File: src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java (hunk 8 above)
Comment (magicDGS) [inline src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java]: Done.

File: src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java (hunk 10 above)
Comment (magicDGS) [inline src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java]: Done.

File: src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java (hunk 11 above)
Comment (magicDGS) [inline src/main/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollection.java]: Done.

File: src/main/java/org/magicdgs/readtools/tools/barcodes/AssignReadGroupByBarcode.java (hunk 12 above)
Comment (magicDGS) [inline src/main/java/org/magicdgs/readtools/tools/barcodes/AssignReadGroupByBarcode.java]: Done.

File: src/main/java/org/magicdgs/readtools/utils/read/RTReadUtils.java (hunk 13 above)
Comment (magicDGS) [inline src/main/java/org/magicdgs/readtools/utils/read/RTReadUtils.java]: Done.

File: src/test/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollectionTest.java (hunk 15 above)
Comment (magicDGS) [inline src/test/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollectionTest.java]: Won't fix, because this requires also the expected class and that's more difficult.

File: src/test/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollectionTest.java (hunk 14 above)
Comment (magicDGS) [inline src/test/java/org/magicdgs/readtools/cmd/argumentcollections/FixBarcodeAbstractArgumentCollectionTest.java]: Done.
