### PR TITLE
Throw user exception for corrupted input

### LINKED ISSUE #359: Catch "Premature end of file" error to throw an user exception for corrupted files
@robmaz reported an UNEXPECTED ERROR while running `TrimReads` with a supposedly corrupted BAM file, which looks that it's comming from the `BlockCompressedInputStream` in HTSJDK:

```
UNEXPECTED ERROR: Premature end of file: /home/vetlinux02/Rupert/prj/Wolbachia/09PoolSeqData/HOT___r05_F180__72.bam
```

The output file is not generated, and the input comes from a ReadTools + Picard (v. 2.12.1-SNAPSHOT) pipeline: 1) StandardizeReads, 2) AssignReadGroupsByBarcode, 3) Picard AddOrReplaceReadGroups and 4) TrimReads

Until we know if the corrupted files are comming from one of the previous steps from the pipeline (which looks unlikely as far as we explore the issue), we can catch the exception (which is a `SAMException`) and rethrow as an `UserException` to show the user that it is corrupted. We should see the exact stack-trace where the problem happen, because maybe it should be catched in the GATK-side.

I will try to get a small corrupted file to test this case.

### PR DESCRIPTION
**Pull request by magicDGS**
Closes #359

### CODE REVIEW

File: src/test/java/org/magicdgs/readtools/engine/sourcehandler/ReadsSourceHandlerUnitTest.java [hunk 1]
```diff
@@ -302,4 +304,16 @@ private static void testHandler(final ReadsSourceHandler handler,
         // test that they close correctly without throwing exceptions
         handler.close();
     }
+
+    @Test
+    public void testCorruptedFileHandler() throws Exception {
+        // TODO - this file is truncated but too big (maybe Rupert can create a better one)
```
Comment (magicDGS) [inline src/test/java/org/magicdgs/readtools/engine/sourcehandler/ReadsSourceHandlerUnitTest.java]: We should probably fix this before merging...

Comment (magicDGS) [reply src/test/java/org/magicdgs/readtools/engine/sourcehandler/ReadsSourceHandlerUnitTest.java]: This cannot be fixed, so I kept a TODO for exploring it when I have more time.
