### PR TITLE
Override Main.handleUserException

### LINKED ISSUE #297: Override handleUserException in Main
After some changes in the GATK framework, they will print on user exception the following:
 
> Set the system property GATK_STACKTRACE_ON_USER_EXCEPTION (--javaOptions '-DGATK_STACKTRACE_ON_USER_EXCEPTION=true') to print the stack trace.

In this case, the `--javaOptions` is for the gatk-launch wrapper, and it will be confusing for our users. In addition, printing the stacktrace should be enabled by default without the extra property for debug mode (similarly to the handleNonUserException). This will make easier debugging and showing the correct information for ReadTools.

### PR DESCRIPTION
**Pull request by magicDGS**
Overrides the handleUserException for avoid GATK's message referring to their system property and the gatk-launch wrapper script while not printing the stack-trace on user exception.

Now the stack-trace is printed for UserExceptions if the DEBUG mode is enabled, the same as the unexpected errors.

Closes #297

### CODE REVIEW

File: src/main/java/org/magicdgs/readtools/Main.java [hunk 1]
```diff
@@ -107,20 +107,38 @@ protected void handleResult(final Object result) {
...
+        printDecoratedExceptionMessage(exceptionOutput, e, "A USER ERROR has occurred: ");
+        printStackTrace(e);
+    }
+
+    /**
+     * Prints in {@link #exceptionOutput} the decorated exception as an unexpected error.
      *
      * In addition, it adds a note pointing to the issue tracker
-     * ({@link RTHelpConstants#ISSUE_TRACKER}).
+     * ({@link RTHelpConstants#ISSUE_TRACKER})
```
Comment (magicDGS) [inline src/main/java/org/magicdgs/readtools/Main.java]: add also the print stack-trace behaviour
