### PR TITLE
FASTQ writer fixes through ReadWriterFactory

### LINKED ISSUE #82: FastqGATKWriter should be more than a wrapper
Currently `FastqGATKWriter` is just a wrapper of HTSJDK `FastqWriter`. Nevertheless, this does not allow to use `Path` or to tune how md5 files are generated and so on (there are some problems on this already reported in HTSJDK).

We can either contribute to HTSJDK to accept `Path` and correct the bugs, or add more control to our custom writer.

### PR DESCRIPTION
**Pull request by magicDGS**
- Fixes #82 by handling FASTQ files in `ReadWriterFactory` as wrapped streams
- Bug fix: Now MD5 digests for FASTQ are made for the file, not for the content
- Support for other compression schemes through Commons Compress (for outputs)
- Applying buffering parameters (`asyncOutputBufferSize` and `bufferSize`) to FASTQ writing
- Method for get a name with barcodes attached (as Illumina) extracted to `RTReadUtils` and used in `FastqGATKWriter`.

### CODE REVIEW

File: src/main/java/org/magicdgs/readtools/utils/read/ReadWriterFactory.java [hunk 1]
```diff
@@ -188,6 +214,49 @@ public GATKReadWriter createWriter(final String output, final SAMFileHeader head
                 "not supported output format based on the extension.");
     }
 
+    private OutputStream getOutputStream(final Path outputPath) {
+        try {
+            // the same as in the SAMFileWriterFactory
```
Comment (magicDGS) [inline src/main/java/org/magicdgs/readtools/utils/read/ReadWriterFactory.java]: This new behaviour requires the change in the md5 computation for FASTQ files.
